/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BrandsTableComponent: typeof import('./components/tables/BrandsTableComponent.vue')['default']
    ButtonComponent: typeof import('./components/ButtonComponent.vue')['default']
    FormComponent: typeof import('./components/forms/FormComponent.vue')['default']
    FormFieldComponent: typeof import('./components/forms/FormFieldComponent.vue')['default']
    MenuItemComponent: typeof import('./components/menu/MenuItemComponent.vue')['default']
    ModelsTableComponent: typeof import('./components/tables/ModelsTableComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceCategoriesTableComponent: typeof import('./components/tables/ServicesCategoriesTableComponent.vue')['default']
    ServicesCategoriesTableComponent: typeof import('./components/tables/ServicesCategoriesTableComponent.vue')['default']
    ServicesPricesTableComponent: typeof import('./components/tables/ServicesPricesTableComponent.vue')['default']
    TableComponent: typeof import('./components/tables/TableComponent.vue')['default']
    VehiclesTableComponent: typeof import('./components/tables/VehiclesTableComponent.vue')['default']
    VehiclesTypesTableComponent: typeof import('./components/tables/VehiclesTypesTableComponent.vue')['default']
  }
}
